# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0020_auto_20160425_1235'),
        ('mood', '0021_auto_20160418_2224'),
    ]

    operations = [
    ]
