# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0024_auto_20160429_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='tod',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening'), ('N', 'Night')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
